title: "Anand Krishnan"
description: "AI/ML Postdoctoral Researcher at Idaho National Laboratory, focused on physics-informed machine learning and adaptive control."
baseurl: "" # set to "/my-github-website" if deploying in a subdirectory
url: "https://anandk97.github.io" #
