title: "Anand Krishnan"
description: "Ph.D. Candidate specializing in data-driven control, optimizations, and efficient manufacturing."
baseurl: "" # set to "/my-github-website" if deploying in a subdirectory
url: "https://anandk97.github.io" #
